# Generated by Django 2.1.5 on 2019-02-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client', models.CharField(max_length=255)),
                ('results', models.CharField(max_length=255)),
                ('image', models.TextField()),
            ],
        ),
    ]
