# Generated by Django 2.1.5 on 2019-02-04 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imgsearch', '0002_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagesearch',
            name='results',
        ),
        migrations.AddField(
            model_name='result',
            name='imageSearch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='imgsearch.ImageSearch'),
            preserve_default=False,
        ),
    ]
