# Generated by Django 2.1.5 on 2019-02-05 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imgsearch', '0004_auto_20190204_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagesearch',
            name='image',
        ),
    ]
