# Generated by Django 2.1.5 on 2019-02-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgsearch', '0006_result_positive_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='positive_feedback',
            field=models.NullBooleanField(),
        ),
    ]
