# Generated by Django 2.1.5 on 2019-02-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgsearch', '0007_auto_20190205_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='positive_feedback',
            field=models.NullBooleanField(default=None),
        ),
    ]
